[MaterialProperties]
	CullMode = "Back"
	DepthOperation = "Less"
	FrontFace = "CCW"
	PrimitiveTopology = "TriangleList"
	PolygonMode = "Fill"

[RenderInfo]
	ColorAttachmentCount = 1
	DepthFormat = "D32_Float"
	ColorFormats = ["RGBA16"]

[Shaders]
	Vertex = "Assets/Shaders/Geometry/Vertex.glsl"
	Fragment = "Assets/Shaders/Geometry/Fragment.glsl"

[DescriptorLayout]
	DescriptorSetLayouts = [[["UniformBuffer", "UniformBuffer", "CombinedImageSampler", "CombinedImageSampler"], 4], [["UniformBuffer", "CombinedImageSampler", "CombinedImageSampler"], 3]]
	DescriptorSetLayoutCount = 2

[PushConstants]
	HasPushConstants = 1
	Size = 212