[Shaders]
	Compute = "Assets/Shaders/Irradiance/Compute.glsl"

[DescriptorLayout]
	DescriptorSetLayouts = [[["StorageImage", "StorageImage"], 2]]
	DescriptorSetLayoutCount = 1

[PushConstants]
	HasPushConstants = 0
	Size = 32