[MaterialProperties]
	CullMode = "None"
	DepthOperation = "Always"
	FrontFace = "CW"
	PrimitiveTopology = "TriangleList"
	PolygonMode = "Fill"

[RenderInfo]
	ColorAttachmentCount = 1
	DepthFormat = "D32_Float"
	ColorFormats = ["RGBA8"]

[Shaders]
	Vertex = "Assets/Shaders/VertexShader.glsl"
	Fragment = "Assets/Shaders/FragmentShader.glsl"

[DescriptorLayout]
	Descriptors = ["CombinedImageSampler"]
	DescriptorCount = 1

[PushConstants]
	HasPushConstants = 1
	Size = 64