[MaterialProperties]
	CullMode = "Front"
	DepthOperation = "Always"
	FrontFace = "CCW"
	PrimitiveTopology = "TriangleList"
	PolygonMode = "Fill"

[RenderInfo]
	ColorAttachmentCount = 2
	DepthFormat = "D32_Float"
	ColorFormats = ["RGBA16", "RG16"]

[Shaders]
	EnableMeshShaders = false
	Vertex = "Assets/Shaders/Skybox/Vertex.glsl"
	Fragment = "Assets/Shaders/Skybox/Fragment.glsl"

[DescriptorLayout]
	DescriptorSetLayouts = [[["Sampler", "SampledImage"], 2]]
	DescriptorSetLayoutCount = 1

[PushConstants]
	HasPushConstants = 1
	Size = 64